### ISSUE TITLE
Package throws "package not installed" error when package is installed but has errors

### ISSUE THREAD

**Issue by SachaG** [tmeasday/check-npm-versions#1]
When using Rebass with Meteor, see: https://github.com/jxnblk/rebass/issues/43

But check-npm-versions throws the same error as if the package just wasn't installed at all.

**Comment by tmeasday** [comment]
I'm not seeing this.

Which version of rebass? And which rc of Meteor?

**Comment by PolGuixe** [comment]
Same issue here: I have opened and issue here: https://github.com/studiointeract/accounts-ui/issues/29

But probably needs to be here.

**Comment by tmeasday** [comment]
I can't reproduce the issue with check-npm-versions 0.2.0 but I released 0.3.0 which hopefully resolves this even though I've consistently failed to repro.
